In [1]:
# some_file.py
import sys
# insert at 1, 0 is the script path (or '' in REPL)
sys.path.insert(1, 'oil_api')
import os
import pandas as pd

In [2]:
import pull

brent-daily:
#     Date        Price
      (date)      (number)
----  ----------  ----------
1     1987-05-20  18.63
2     1987-05-21  18.45
3     1987-05-22  18.55
4     1987-05-25  18.6
5     1987-05-26  18.63
6     1987-05-27  18.6
7     1987-05-28  18.6
8     1987-05-29  18.58
9     1987-06-01  18.65
10    1987-06-02  18.68
11    1987-06-03  18.75
12    1987-06-04  18.78
13    1987-06-05  18.65
14    1987-06-08  18.75
15    1987-06-09  18.78
16    1987-06-10  18.78
17    1987-06-11  18.68
18    1987-06-12  18.78
19    1987-06-16  18.9
20    1987-06-17  19.03
...
100   1987-10-07  18.58
101   1987-10-08  18.63
102   1987-10-09  18.6
103   1987-10-12  18.55
104   1987-10-13  18.55
105   1987-10-14  18.68
106   1987-10-15  18.68
107   1987-10-16  19
108   1987-10-19  19.1
109   1987-10-20  18.78
110   1987-10-21  18.93
...
1000  1991-04-17  19.85
1001  1991-04-18  19.4
1002  1991-04-19  19.18
1003  1991-04-22  19.78
1004  1991-04-23  19.6
1005  1991-04-24  19.55
1006  1991-04-25  19.6
1007  1991-04-26  19.63
1008  1991-04-29  19.95
1009  1991-04-30  19.7
1010  1991-05-01  19.7
...
8354  2020-04-15  19.8
8355  2020-04-16  18.69
8356  2020-04-17  19.75
8357  2020-04-20  17.36
8358  2020-04-21  9.12
8359  2020-04-22  13.77
8360  2020-04-23  15.06
8361  2020-04-24  15.87
8362  2020-04-27  15.17
8363  None        None
brent-week:
#     Date        Price
      (date)      (number)
----  ----------  ----------
1     1987-05-15  18.58
2     1987-05-22  18.54
3     1987-05-29  18.6
4     1987-06-05  18.7
5     1987-06-12  18.75
6     1987-06-19  19.01
7     1987-06-26  18.91
8     1987-07-03  19.16
9     1987-07-10  19.57
10    1987-07-17  20.2
11    1987-07-24  20.19
12    1987-07-31  19.86
13    1987-08-07  20.16
14    1987-08-14  19.41
15    1987-08-21  18.5
16    1987-08-28  17.92
17    1987-09-04  18.35
18    1987-09-11  17.93
19    1987-09-18  18.39
20    1987-09-25  18.5
...
100   1989-04-07  19.56
101   1989-04-14  19.8
102   1989-04-21  21.09
103   1989-04-28  20.84
104   1989-05-05  19.28
105   1989-05-12  19.04
106   1989-05-19  18.9
107   1989-05-26  17.82
108   1989-06-02  18.05
109   1989-06-09  18.19
110   1989-06-16  16.9
...
1000  2006-07-07  73.45
1001  2006-07-14  73.99
1002  2006-07-21  73.52
1003  2006-07-28  73.53
1004  2006-08-04  76.32
1005  2006-08-11  76.98
1006  2006-08-18  72.35
1007  2006-08-25  71.92
1008  2006-09-01  68.35
1009  2006-09-08  65.76
1010  2006-09-15  61.38
...
1712  2020-02-28  54.09
1713  2020-03-06  50.7
1714  2020-03-13  33.72
1715  2020-03-20  25.65
1716  2020-03-27  23.96
1717  2020-04-03  18.72
1718  2020-04-10  22.53
1719  2020-04-17  20
1720  2020-04-24  14.24
1721  None        None
brent-month:
#    Date        Price
     (date)      (number)
---  ----------  ----------
1    1987-05-15  18.58
2    1987-06-15  18.86
3    1987-07-15  19.86
4    1987-08-15  18.98
5    1987-09-15  18.31
6    1987-10-15  18.76
7    1987-11-15  17.78
8    1987-12-15  17.05
9    1988-01-15  16.75
10   1988-02-15  15.73
11   1988-03-15  14.73
12   1988-04-15  16.6
13   1988-05-15  16.31
14   1988-06-15  15.54
15   1988-07-15  14.91
16   1988-08-15  14.89
17   1988-09-15  13.18
18   1988-10-15  12.41
19   1988-11-15  13.02
20   1988-12-15  15.31
...
100  1995-08-15  16.1
101  1995-09-15  16.7
102  1995-10-15  16.11
103  1995-11-15  16.86
104  1995-12-15  17.93
105  1996-01-15  17.85
106  1996-02-15  18
107  1996-03-15  19.85
108  1996-04-15  20.9
109  1996-05-15  19.15
110  1996-06-15  18.46
...
387  2019-07-15  63.92
388  2019-08-15  59.04
389  2019-09-15  62.83
390  2019-10-15  59.71
391  2019-11-15  63.21
392  2019-12-15  67.31
393  2020-01-15  63.65
394  2020-02-15  55.66
395  2020-03-15  32.01
396  None        None
brent-year:
#    Date        Price
     (date)      (number)
---  ----------  ----------
1    1987-06-30  18.53
2    1988-06-30  14.91
3    1989-06-30  18.23
4    1990-06-30  23.76
5    1991-06-30  20.04
6    1992-06-30  19.32
7    1993-06-30  17.01
8    1994-06-30  15.86
9    1995-06-30  17.02
10   1996-06-30  20.64
11   1997-06-30  19.11
12   1998-06-30  12.76
13   1999-06-30  17.9
14   2000-06-30  28.66
15   2001-06-30  24.46
16   2002-06-30  24.99
17   2003-06-30  28.85
18   2004-06-30  38.26
19   2005-06-30  54.57
20   2006-06-30  65.16
...
24   2010-06-30  79.61
25   2011-06-30  111.26
26   2012-06-30  111.63
27   2013-06-30  108.56
28   2014-06-30  98.97
29   2015-06-30  52.32
30   2016-06-30  43.64
31   2017-06-30  54.13
32   2018-06-30  71.34
33   None        None
wti-daily:
#     Date        Price
      (date)      (number)
----  ----------  ----------
1     1986-01-02  25.56
2     1986-01-03  26
3     1986-01-06  26.53
4     1986-01-07  25.85
5     1986-01-08  25.87
6     1986-01-09  26.03
7     1986-01-10  25.65
8     1986-01-13  25.08
9     1986-01-14  24.97
10    1986-01-15  25.18
11    1986-01-16  23.98
12    1986-01-17  23.63
13    1986-01-20  21.33
14    1986-01-21  20.61
15    1986-01-22  20.25
16    1986-01-23  19.93
17    1986-01-24  19.45
18    1986-01-27  20.87
19    1986-01-28  19.45
20    1986-01-29  19.61
...
100   1986-05-23  16.95
101   1986-05-27  15.1
102   1986-05-28  14.65
103   1986-05-29  14.5
104   1986-05-30  14.3
105   1986-06-02  13.8
106   1986-06-03  13.35
107   1986-06-04  13.15
108   1986-06-05  13.21
109   1986-06-06  12.73
110   1986-06-09  12.61
...
1000  1989-12-01  20.26
1001  1989-12-04  20.24
1002  1989-12-05  20.22
1003  1989-12-06  20.46
1004  1989-12-07  20.45
1005  1989-12-08  20.41
1006  1989-12-11  20.69
1007  1989-12-12  20.8
1008  1989-12-13  20.75
1009  1989-12-14  20.67
1010  1989-12-15  21.13
...
8641  2020-04-15  19.96
8642  2020-04-16  19.82
8643  2020-04-17  18.31
8644  2020-04-20  -36.98
8645  2020-04-21  8.91
8646  2020-04-22  13.64
8647  2020-04-23  15.06
8648  2020-04-24  15.99
8649  2020-04-27  12.17
8650  None        None
wti-week:
#     Date        Price
      (date)      (number)
----  ----------  ----------
1     1986-01-03  25.78
2     1986-01-10  25.99
3     1986-01-17  24.57
4     1986-01-24  20.31
5     1986-01-31  19.69
6     1986-02-07  16.72
7     1986-02-14  16.25
8     1986-02-21  14.39
9     1986-02-28  14.25
10    1986-03-07  12.27
11    1986-03-14  13.07
12    1986-03-21  13.45
13    1986-03-28  12
14    1986-04-04  11.44
15    1986-04-11  13.46
16    1986-04-18  12.16
17    1986-04-25  13.44
18    1986-05-02  13.76
19    1986-05-09  15.08
20    1986-05-16  15.74
...
100   1987-11-27  18.83
101   1987-12-04  18.62
102   1987-12-11  18.34
103   1987-12-18  16.35
104   1987-12-25  16.23
105   1988-01-01  16.78
106   1988-01-08  17.6
107   1988-01-15  16.79
108   1988-01-22  17.2
109   1988-01-29  16.92
110   1988-02-05  17.08
...
1000  2005-02-25  51.75
1001  2005-03-04  52.74
1002  2005-03-11  54.22
1003  2005-03-18  55.93
1004  2005-03-25  52.95
1005  2005-04-01  54.97
1006  2005-04-08  55.24
1007  2005-04-15  51.44
1008  2005-04-22  52.39
1009  2005-04-29  52
1010  2005-05-06  50.64
...
1783  2020-02-28  48.36
1784  2020-03-06  45.57
1785  2020-03-13  32.39
1786  2020-03-20  24.19
1787  2020-03-27  19.44
1788  2020-04-03  21.69
1789  2020-04-10  24.41
1790  2020-04-17  20.12
1791  2020-04-24  3.32
1792  None        None
wti-month:
#    Date        Price
     (date)      (number)
---  ----------  ----------
1    1986-01-15  22.93
2    1986-02-15  15.46
3    1986-03-15  12.61
4    1986-04-15  12.84
5    1986-05-15  15.38
6    1986-06-15  13.43
7    1986-07-15  11.59
8    1986-08-15  15.1
9    1986-09-15  14.87
10   1986-10-15  14.9
11   1986-11-15  15.22
12   1986-12-15  16.11
13   1987-01-15  18.65
14   1987-02-15  17.75
15   1987-03-15  18.3
16   1987-04-15  18.68
17   1987-05-15  19.44
18   1987-06-15  20.07
19   1987-07-15  21.34
20   1987-08-15  20.31
...
100  1994-04-15  16.42
101  1994-05-15  17.89
102  1994-06-15  19.06
103  1994-07-15  19.66
104  1994-08-15  18.38
105  1994-09-15  17.45
106  1994-10-15  17.72
107  1994-11-15  18.07
108  1994-12-15  17.16
109  1995-01-15  18.04
110  1995-02-15  18.57
...
403  2019-07-15  57.35
404  2019-08-15  54.81
405  2019-09-15  56.95
406  2019-10-15  53.96
407  2019-11-15  57.03
408  2019-12-15  59.88
409  2020-01-15  57.52
410  2020-02-15  50.54
411  2020-03-15  29.21
412  None        None
wti-year:
#    Date        Price
     (date)      (number)
---  ----------  ----------
1    1986-06-30  15.05
2    1987-06-30  19.2
3    1988-06-30  15.97
4    1989-06-30  19.64
5    1990-06-30  24.53
6    1991-06-30  21.54
7    1992-06-30  20.58
8    1993-06-30  18.43
9    1994-06-30  17.2
10   1995-06-30  18.43
11   1996-06-30  22.12
12   1997-06-30  20.61
13   1998-06-30  14.42
14   1999-06-30  19.34
15   2000-06-30  30.38
16   2001-06-30  25.98
17   2002-06-30  26.18
18   2003-06-30  31.08
19   2004-06-30  41.51
20   2005-06-30  56.64
...
26   2011-06-30  94.88
27   2012-06-30  94.05
28   2013-06-30  97.98
29   2014-06-30  93.17
30   2015-06-30  48.66
31   2016-06-30  43.29
32   2017-06-30  50.8
33   2018-06-30  65.23
34   2019-06-30  57
35   None        None

In [3]:
brent_daily = pd.read_csv('oil_api/data/brent_daily.csv')  
wti_daily = pd.read_csv('oil_api/data/wti_daily.csv')

In [4]:
#brent_daily = brent_daily.set_index('Date')
brent_daily = brent_daily.rename(columns={'Price':'Brent_Price_USD'})
#wti_daily = wti_daily.set_index('Date')
wti_daily = wti_daily.rename(columns={'Price':'WTI_Price_USD'})

In [5]:

oil_daily = pd.concat([brent_daily, wti_daily], axis=1).reindex(brent_daily.index)

In [6]:
oil_daily

            Date  Brent_Price_USD        Date  WTI_Price_USD
0     1987-05-20            18.63  1986-01-02          25.56
1     1987-05-21            18.45  1986-01-03          26.00
2     1987-05-22            18.55  1986-01-06          26.53
3     1987-05-25            18.60  1986-01-07          25.85
4     1987-05-26            18.63  1986-01-08          25.87
...          ...              ...         ...            ...
8357  2020-04-21             9.12  2019-02-27          56.92
8358  2020-04-22            13.77  2019-02-28          57.21
8359  2020-04-23            15.06  2019-03-01          55.76
8360  2020-04-24            15.87  2019-03-04          56.60
8361  2020-04-27            15.17  2019-03-05          56.55

[8362 rows x 4 columns]

In [7]:
oil_daily.to_csv('data/exported_data/daily_oil_prices_87_20.csv')

'oil_api/datapackage.json'