In [1]:
import pandas as pd
from datetime import datetime as dt

In [2]:
OPEC_April_MOMRreport_file = 'data/MOMR Appendix Tables (April 2020).xlsx'

OPEC_demand_supply_balance_df = pd.read_excel(OPEC_April_MOMRreport_file,sheet_name=1)
OPEC_demand_supply_balance_column_names = OPEC_demand_supply_balance_df.iloc[3,1:15].values.copy()

OPEC_demand_supply_balance_cleaned_df = OPEC_demand_supply_balance_df.iloc[4:,1:15].copy()
OPEC_demand_supply_balance_cleaned_df.reset_index(drop=True,inplace=True)
OPEC_demand_supply_balance_cleaned_df.columns = OPEC_demand_supply_balance_column_names
OPEC_demand_supply_balance_cleaned_df

,NaN,2016.0,2017.0,2018.0,1Q19,2Q19,3Q19,4Q19,2019.0,1Q20,2Q20,3Q20,4Q20,2020.0
0,World oil demand and supply balance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,World demand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,OECD,47.065508,47.606068,48.005391,47.7192,47.1467,48.4563,48.2926,47.906771,45.5314,38.3696,45.1701,46.5463,43.915536
3,Americas,24.890128,25.070255,25.602118,25.135,25.292,26.0292,25.99,25.615045,24.5539,20.3458,24.7792,25.2649,23.744299
4,Europe,14.036516,14.384468,14.326888,14.0882,14.2478,14.751,14.248,14.335326,13.0998,11.37,13.5532,13.7805,12.955458
5,Asia Pacific,8.138863,8.151345,8.076385,8.49593,7.60685,7.67612,8.05463,7.956400,7.87763,6.65385,6.83767,7.50092,7.215780
6,DCs,31.563791,32.132911,32.620619,32.9578,32.8388,33.4148,33.1018,33.079625,31.9159,30.561,31.4248,32.0023,31.477627
7,FSU,4.571600,4.643022,4.755528,4.69762,4.677,4.95543,5.03703,4.843008,4.4976,4.37664,4.55133,4.70933,4.534649
8,Other Europe,0.695717,0.717675,0.742675,0.751623,0.708652,0.748828,0.840772,0.762676,0.707623,0.640652,0.569784,0.664219,0.645444
9,China,11.800905,12.320792,12.712059,12.6267,13.1903,12.9526,13.5195,13.074375,10.2697,12.7498,12.5666,13.3797,12.246680
10,(a) Total world demand,95.697522,97.420469,98.836272,98.7529,98.5614,100.528,100.792,99.666454,92.9222,86.6978,94.2827,97.3018,92.819937
11,Non-OPEC liquids production,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,OECD,24.863795,25.710779,28.325075,29.3195,29.6401,29.7439,31.0249,29.936266,31.1227,29.8163,29.6286,29.3589,29.978973
13,Americas,20.585297,21.492315,24.076055,25.0652,25.5882,25.6854,26.6226,25.744428,26.5477,25.3634,25.0931,24.6617,25.413530
14,Europe,3.853205,3.826702,3.841007,3.82398,3.57458,3.54618,3.88498,3.707152,4.05984,3.9111,3.95807,4.12024,4.012458
15,Asia Pacific,0.425292,0.391762,0.408014,0.43037,0.47737,0.51237,0.51737,0.484685,0.515116,0.541808,0.577448,0.577032,0.552984
16,DCs,14.097711,13.942664,14.020702,14.0287,14.0977,14.2487,14.4657,14.211507,14.48,14.0552,14.173,14.2332,14.235172
17,FSU,13.851691,14.049373,14.290646,14.5525,14.1581,14.3437,14.4223,14.368703,14.5037,11.8243,12.4281,12.4262,12.793560
18,Other Europe,0.133404,0.127735,0.124488,0.122326,0.122326,0.122326,0.119326,0.121570,0.119843,0.117445,0.115126,0.112891,0.116314
19,China,4.090145,3.969115,3.976583,4.04761,4.07661,4.04661,4.03361,4.051058,4.04303,3.99982,3.98976,4.00954,4.010477
20,Processing gains,2.194000,2.218000,2.250000,2.278,2.278,2.278,2.278,2.278000,2.332,2.332,2.332,2.332,2.332000
21,Total non-OPEC liquids production,59.230747,60.017665,62.987495,64.3486,64.3728,64.7832,66.3438,64.967103,66.6013,62.145,62.6667,62.4727,63.466495
22,OPEC NGLs + \nnon-conventional oils,4.571893,4.628041,4.752580,4.79007,4.81208,4.70407,4.85307,4.789763,4.88207,4.81907,4.81907,4.81907,4.834739
23,(b) Total non-OPEC liquids production and OPEC...,63.802640,64.645706,67.740075,69.1387,69.1849,69.4873,71.1969,69.756866,71.4833,66.9641,67.4857,67.2918,68.301234
24,OPEC crude oil production \n(secondary sources),31.663242,31.483833,31.344268,29.9583,29.452,28.8621,29.0956,29.338320,28.2641,NaN,NaN,NaN,NaN
25,Total liquids production,95.465882,96.129539,99.084343,99.097,98.6369,98.3494,100.293,99.095186,99.7475,NaN,NaN,NaN,NaN
26,Balance (stock change and miscellaneous),-0.231641,-1.290930,0.248071,0.344176,0.0754918,-2.17857,-0.499238,-0.571268,6.8253,NaN,NaN,NaN,NaN
27,"OECD closing stock levels, mb",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Commercial,3007.293000,2859.540000,2873.147000,2876.65,2935.88,2944.61,2901.69,2901.695000,NaN,NaN,NaN,NaN,NaN
29,SPR,1600.951000,1568.923000,1551.723000,1556.92,1548.81,1544.48,1535.34,1535.340000,NaN,NaN,NaN,NaN,NaN
30,Total,4608.244000,4428.463000,4424.870000,4433.57,4484.69,4489.08,4437.03,4437.035000,NaN,NaN,NaN,NaN,NaN
31,Oil-on-water,1102.455638,1025.065438,1058.455638,1013.46,995.456,1012.46,1011.46,1011.455638,NaN,NaN,NaN,NaN,NaN
32,"Days of forward consumption in OECD, days",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Commercial onland stocks,63.170371,59.567060,59.973715,61.015,60.5883,60.9743,63.7296,66.074452,NaN,NaN,NaN,NaN,NaN
34,SPR,33.629137,32.682225,32.390474,33.023,31.963,31.9816,33.7205,34.961203,NaN,NaN,NaN,NaN,NaN
35,Total,96.799508,92.249285,92.364189,94.0379,92.5512,92.9559,97.4501,101.035655,NaN,NaN,NaN,NaN,NaN
36,Memo items,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,(a) - (b),31.894883,32.774763,31.096197,29.6141,29.3765,31.0406,29.5949,29.909588,21.4388,19.7337,26.7969,30.01,24.518703
38,Note: Non-OPEC liquids production includes th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Totals may not add up due to indepe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Source: OPEC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
OPEC_world_rig_counts_df = pd.read_excel(OPEC_April_MOMRreport_file,sheet_name=5)

OPEC_world_rig_counts_df_column_names_series = OPEC_world_rig_counts_df.iloc[4,1:]
OPEC_world_rig_counts_df_column_names = OPEC_world_rig_counts_df_column_names_series.values.copy()
OPEC_world_rig_counts_df_column_names[4] = 'Change 2019/18'
OPEC_world_rig_counts_df_column_names[9] = dt.strftime(OPEC_world_rig_counts_df_column_names[9],'%b %d')
OPEC_world_rig_counts_df_column_names[10] = dt.strftime(OPEC_world_rig_counts_df_column_names[10],'%b %d')
OPEC_world_rig_counts_df_column_names[11] = 'Change Mar/Feb'

OPEC_world_rig_counts_cleaned_df = OPEC_world_rig_counts_df.iloc[5:,1:].copy()
OPEC_world_rig_counts_cleaned_df.reset_index(drop=True,inplace=True)
OPEC_world_rig_counts_cleaned_df.columns = OPEC_world_rig_counts_df_column_names
OPEC_world_rig_counts_cleaned_df

,NaN,2017.0,2018.0,2019.0,Change 2019/18,2Q19,3Q19,4Q19,1Q20,Feb 01,Mar 01,Change Mar/Feb
0,World rig count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,US,874.750000,1031.333333,943.500000,-87.8333,989.667,920,819,784.333,790,771,-19
2,Canada,206.583333,191.166667,134.416667,-56.75,83,131,138.333,195.667,249,133,-116
3,Mexico,17.416667,26.583333,36.500000,9.91667,33.6667,38,48,45.6667,49,42,-7
4,OECD Americas,1098.750000,1249.083333,1114.416667,-134.667,1106.33,1089,1005.33,1025.67,1088,946,-142
5,Norway,14.750000,15.000000,17.000000,2,16.6667,18.3333,17.6667,16.3333,17,14,-3
6,UK,8.750000,7.166667,14.583333,7.41667,15.6667,16.3333,13.3333,7.66667,7,6,-1
7,OECD Europe,91.916667,85.333333,148.500000,63.1667,159,189.667,153.667,128.667,130,123,-7
8,OECD Asia Pacific,15.333333,20.583333,28.583333,8,29.3333,31.3333,30,29.6667,29,32,3
9,Total OECD,1206.000000,1355.000000,1291.500000,-63.5,1294.67,1310,1189,1184,1247,1101,-146
10,Other Asia*,207.916667,222.000000,221.416667,-0.583333,225,216.667,211.667,214,213,218,5
11,Latin America,118.583333,131.000000,129.250000,-1.75,129.667,131.667,119,106.667,110,102,-8
12,Middle East,68.166667,64.666667,68.083333,3.41667,69.3333,67.3333,69.3333,69.3333,69,70,1
13,Africa,37.750000,44.583333,55.333333,10.75,52.6667,51,62.6667,60.6667,60,59,-1
14,Total DCs,432.416667,462.250000,474.083333,11.8333,476.667,466.667,462.667,450.667,452,449,-3
15,Non-OPEC rig count,1638.416667,1817.250000,1765.583333,-51.6667,1771.33,1776.67,1651.67,1634.67,1699,1550,-149
16,Algeria,53.500000,49.833333,44.916667,-4.91667,49.3333,42.3333,41.3333,37.6667,38,34,-4
17,Angola,2.750000,3.666667,4.416667,0.75,5,4.33333,3.33333,6,6,6,0
18,Congo,1.750000,3.166667,3.166667,0,4,3,2,2,2,2,0
19,Equatorial Guinea**,1.000000,1.000000,2.000000,1,2,2,2,2,2,2,0
20,Gabon,0.916667,3.416667,7.166667,3.75,6.33333,6.66667,8.66667,8.66667,9,8,-1
21,Iran**,155.500000,157.000000,157.000000,0,157,157,157,157,157,157,0
22,Iraq,49.166667,59.333333,73.583333,14.25,75,77,77,74.3333,72,74,2
23,Kuwait,53.666667,50.666667,45.583333,-5.08333,44.3333,46.3333,48,52.6667,55,50,-5
24,Libya,1.000000,4.583333,14.416667,9.83333,15,15.6667,16,14.3333,16,11,-5
25,Nigeria,8.500000,13.250000,15.583333,2.33333,14,15.6667,18.3333,19.3333,23,21,-2
26,Saudi Arabia,118.166667,116.916667,115.000000,-1.91667,115,117.667,109.333,113,114,114,0
27,UAE,51.666667,55.166667,62.083333,6.91667,59.3333,64.3333,66.6667,66.3333,65,68,3
28,Venezuela,49.083333,32.333333,24.500000,-7.83333,22.6667,25,25,25,25,25,0
29,OPEC rig count,546.666667,550.333333,569.416667,19.0833,569,577,574.667,578.333,584,572,-12
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,World rig count***,2185.083333,2367.583333,2335.000000,-32.5833,2340.33,2353.67,2226.33,2213,2283,2122,-161
32,of which:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Oil,1677.583333,1886.333333,1840.083333,-46.25,1829,1835.33,1758,1748.33,1808,1677,-131
34,Gas,465.500000,448.333333,463.583333,15.25,482.333,486,430.667,411,420,381,-39
35,Others,42.000000,32.916667,31.333333,-1.58333,29,32.3333,37.6667,53.6667,55,64,9
36,Note: * Other Asia includes Indonesia.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,** Estimated data when Baker Hughes...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,*** Data excludes China and FSU.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Totals may not add up due to indepe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Sources: Baker Hughes and OPEC.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN